<?php
/**
 * Initialize the options before anything else.
 */
add_action( 'admin_init', 'custom_theme_options', 1 );

/**
 * Build the custom settings & update OptionTree.
 */
function custom_theme_options() {
  /**
   * Get a copy of the saved settings array.
   */
  $saved_settings = get_option( 'option_tree_settings', array() );

  /**
   * Custom settings array that will eventually be
   * passes to the OptionTree Settings API Class.
   */
  $custom_settings = array(
    'contextual_help' => array(
      'content'       => array(
        array(
          'id'        => 'general_help',
          'title'     => __('General', 'asana'),
          'content'   => __('Theme options here.', 'asana')
        )
      ),
      'sidebar'       => '',
    ),
    'sections'        => array(
      array(
        'id'          => 'general',
        'title'       => __('General', 'asana')
      ),
      array(
        'id'          => 'logo',
        'title'       => __('Logo settings', 'asana')
      ),
      array(
        'id'          => 'color',
        'title'       => __('Colour schemes', 'asana')
      ),
      array(
        'id'          => 'fonts',
        'title'       => __('Fonts', 'asana')
      ),
      array(
        'id'          => 'headers',
        'title'       => __('Page headers settings', 'asana')
      ),
      array(
        'id'          => 'home',
        'title'       => __('"Home" page settings', 'asana')
      ),
      array(
        'id'          => 'contact',
        'title'       => __('"Contact" page settings', 'asana')
      ),
      array(
        'id'          => 'mailchimp',
        'title'       => __('Mailchimp settings', 'asana')
      ),
      array(
        'id'          => 'social',
        'title'       => __('Socials', 'asana')
      )
    ),
    'settings'        => array(
      array(
        'id'          => 'uni_general_info_textblock',
        'label'       => __( 'General information about hosting environment', 'asana' ),
        'desc'        => sprintf( __( 'Curl extension is required for Mailchimp subscribe form to function properly. Status of curl extension: %s', 'asana' ), (function_exists('curl_version') ? '<span style="color:green">Enabled<span>' : '<span style="color:red">Disabled<span>')),
        'std'         => '',
        'type'        => 'textblock-titled',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_ajax_scroll_enable_products',
        'label'       => sprintf( __( 'Enable/disable infinite ajax scroll for %s', 'asana' ), __('products', 'asana') ),
        'desc'        => sprintf( __( 'You can switch between regular pagination and infinite ajax scroll feature, when all you %s will be loaded via ajax on archive pages and also automatically when user scrolls to the end of the current page.', 'asana' ), __('products', 'asana') ),
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_ajax_scroll_enable_posts',
        'label'       => sprintf( __( 'Enable/disable infinite ajax scroll for %s', 'asana' ), __('posts', 'asana') ),
        'desc'        => sprintf( __( 'You can switch between regular pagination and infinite ajax scroll feature, when all you %s will be loaded via ajax on archive pages and also automatically when user scrolls to the end of the current page.', 'asana' ), __('posts', 'asana') ),
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_ajax_scroll_enable_events',
        'label'       => sprintf( __( 'Enable/disable infinite ajax scroll for %s', 'asana' ), __('events', 'asana') ),
        'desc'        => sprintf( __( 'You can switch between regular pagination and infinite ajax scroll feature, when all you %s will be loaded via ajax on archive pages and also automatically when user scrolls to the end of the current page.', 'asana' ), __('events', 'asana') ),
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_events_page',
        'label'       => __( 'Events page', 'asana' ),
        'desc'        => __( 'Select your Events page. This page is like a blog, but for events. A link to this page will be added on a single event page. It acts like a global option and this value can be overrided for every single event page. It is useful if you have several different pages with events.', 'asana' ),
        'std'         => '',
        'type'        => 'custom-post-type-select',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => 'page',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_events_join_on',
        'label'       => __( 'Enable/disable "join event" functionality', 'asana' ),
        'desc'        => __( 'You can enable/disable "join" functionality on single event pages. Enabling adds "Join" button to all single event pages. This button opens modal window with form that can be used as registration form. After form submit a site owner and a user receive emails with entered information. <strong>Important: no data from this form will be stored in DB. It just sends emails!</strong>', 'asana' ),
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_footer_textblock',
        'label'       => __( 'Footer Textblock', 'asana' ),
        'desc'        => __( 'Below are some settings for the footer.', 'asana' ),
        'std'         => '',
        'type'        => 'textblock',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_footer_text',
        'label'       => __( 'Text in the footer', 'asana' ),
        'desc'        => __( 'Add your own text to the footer', 'asana' ),
        'std'         => '',
        'type'        => 'textarea',
        'section'     => 'general',
        'rows'        => '5',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_logo_textblock',
        'label'       => __( 'Textblock', 'asana' ),
        'desc'        => __( 'You can swicth between two options how your logo has to be shown: by using two .png files of the same image but in different colours or by using one image in SVG format. We also recommend you to use images with transparent background for the best effect!', 'asana' ),
        'std'         => '',
        'type'        => 'textblock',
        'section'     => 'logo',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_logo_type',
        'label'       => __( 'Switch to logo in SVG format?', 'asana' ),
        'desc'        => __( '"On" means that you want to use logo in SVG format. "Off" means that you want to use two uploaded images.', 'asana' ),
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'logo',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_logo_a',
        'label'       => __( 'Logo A', 'asana' ),
        'desc'        => __( 'Upload the first variant of your logo. By default, the header initially is white. So, it is a good idea to add a dark variant of your logo.', 'asana' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'logo',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_logo_b',
        'label'       => __( 'Logo B', 'asana' ),
        'desc'        => __( 'Upload the second variant of your logo. Now, it is better to add a light variant of your logo. Something that contrasting with the first variant.', 'asana' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'logo',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_logo_svg',
        'label'       => __( 'Logo in SVG format', 'asana' ),
        'desc'        => __( 'Add the code here.', 'asana' ),
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'logo',
        'rows'        => '10',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_color_schemes',
        'label'       => __( 'Colour schemes', 'asana' ),
        'desc'        => __( 'You can choose a desired colour scheme here. The default is the first one.', 'asana' ),
        'std'         => 'default',
        'type'        => 'radio-image',
        'section'     => 'color',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_google_fonts',
        'label'       => __( 'Custom Google Fonts', 'asana' ),
        'desc'        => __( 'You can define custom Google fonts here. Please, use the first for regular text and the second for headings. Default are: Lato (300, 300italic, regular) and Montserrat (700, regular)', 'asana' ),
        'std'         => array(
          array(
            'family'    => 'lato',
            'variants'  => array( '300', '300italic', 'regular' ),
            'subsets'   => array( 'latin' )
          ),
          array(
            'family'    => 'montserrat',
            'variants'  => array( '700', 'regular' ),
            'subsets'   => array( 'latin' )
          )
        ),
        'type'        => 'google-fonts',
        'section'     => 'fonts',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_shop_header_bg',
        'label'       => __( 'Page header image on Shop/Product archives/Single product pages', 'asana' ),
        'desc'        => __( 'This image will be shown on the top of the Shop/Product archives/Single product pages', 'asana' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'headers',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_shop_header_title',
        'label'       => __( 'Page header title on Shop/Single product pages', 'asana' ),
        'desc'        => __( 'This title will be shown on the top of the Shop/Single product pages', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'headers',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_shop_header_title_color',
        'label'       => __( 'Colour of page header title on Shop/Single product pages', 'asana' ),
        'desc'        => __( 'Default is "white". You can choose another colour for this text.', 'asana' ),
        'std'         => '#ffffff',
        'type'        => 'colorpicker',
        'section'     => 'headers',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_cart_header_bg',
        'label'       => __( 'Page header image on Cart page', 'asana' ),
        'desc'        => __( 'This image will be shown on the top of the Cart page', 'asana' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'headers',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_cart_header_title',
        'label'       => __( 'Page header title on Cart page', 'asana' ),
        'desc'        => __( 'This title will be shown on the top of the Cart page', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'headers',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_cart_header_title_color',
        'label'       => __( 'Colour of page header title on Cart page', 'asana' ),
        'desc'        => __( 'Default is "white". You can choose another colour for this text.', 'asana' ),
        'std'         => '#ffffff',
        'type'        => 'colorpicker',
        'section'     => 'headers',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_checkout_header_bg',
        'label'       => __( 'Page header image on Checkout page', 'asana' ),
        'desc'        => __( 'This image will be shown on the top of the Checkout page', 'asana' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'headers',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_checkout_header_title',
        'label'       => __( 'Page header title on Checkout page', 'asana' ),
        'desc'        => __( 'This title will be shown on the top of the Checkout page', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'headers',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_checkout_header_title_color',
        'label'       => __( 'Colour of page header title on Checkout page', 'asana' ),
        'desc'        => __( 'Default is "white". You can choose another colour for this text.', 'asana' ),
        'std'         => '#ffffff',
        'type'        => 'colorpicker',
        'section'     => 'headers',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_about_header_bg',
        'label'       => __( 'Page header image on "About" page', 'asana' ),
        'desc'        => __( 'This image will be shown on the top of "About" page', 'asana' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'headers',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_about_header_title',
        'label'       => __( 'Page header title on "About" page', 'asana' ),
        'desc'        => __( 'This title will be shown on the top of "About" page', 'asana' ),
        'std'         => 'About Our Studio',
        'type'        => 'text',
        'section'     => 'headers',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_about_header_title_color',
        'label'       => __( 'Colour of page header title on "About" page', 'asana' ),
        'desc'        => __( 'Default is "white". You can choose another colour for this text.', 'asana' ),
        'std'         => '#ffffff',
        'type'        => 'colorpicker',
        'section'     => 'headers',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_events_header_bg',
        'label'       => __( 'Page header image on "Events" page', 'asana' ),
        'desc'        => __( 'This image will be shown on the top of "Events" page', 'asana' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'headers',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_events_header_title',
        'label'       => __( 'Page header title on "Events" page', 'asana' ),
        'desc'        => __( 'This title will be shown on the top of "Events" page', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'headers',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_events_header_title_color',
        'label'       => __( 'Colour of page header title on "Events" page', 'asana' ),
        'desc'        => __( 'Default is "white". You can choose another colour for this text.', 'asana' ),
        'std'         => '#ffffff',
        'type'        => 'colorpicker',
        'section'     => 'headers',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_contact_header_bg',
        'label'       => __( 'Page header image on Contact page', 'asana' ),
        'desc'        => __( 'This image will be shown on the top of the Contact page', 'asana' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'headers',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_contact_header_title',
        'label'       => __( 'Page header title on Contact page', 'asana' ),
        'desc'        => __( 'This title will be shown on the top of the Contact page', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'headers',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_contact_header_title_color',
        'label'       => __( 'Colour of page header title on Contact page', 'asana' ),
        'desc'        => __( 'Default is "white". You can choose another colour for this text.', 'asana' ),
        'std'         => '#ffffff',
        'type'        => 'colorpicker',
        'section'     => 'headers',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_rev_slider_enable',
        'label'       => __( 'Show/hide Revolution Slider on home page', 'asana' ),
        'desc'        => __( 'Important: you must activate "Revolution Slider" plugin first (bundled with a theme) and create a slider with alias "home"!', 'asana' ),
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_slider_enable',
        'label'       => __( 'Show/hide the slider on home page', 'asana' ),
        'desc'        => __( 'A simple yet functional slider. Utilises custom post types "Home slides". Each post under "Home slides" acts like a slide for this slider.', 'asana' ),
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_about_enable',
        'label'       => __( 'Show/hide the "About Us" block on home page', 'asana' ),
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_about_title',
        'label'       => __( 'Title for the "About Us" block on home page', 'asana' ),
        'desc'        => __( 'Add custom title for this block', 'asana' ),
        'std'         => __( 'About Us', 'asana' ),
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_about_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_about_text',
        'label'       => __( 'Custom text for the "About Us" block on home page', 'asana' ),
        'desc'        => __( 'Add custom text for the "About Us" block on home page', 'asana' ),
        'std'         => '',
        'type'        => 'textarea',
        'section'     => 'home',
        'rows'        => '5',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_about_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_about_image',
        'label'       => __( 'Image for "About Us" block on home page', 'asana' ),
        'desc'        => __( 'Upload an image for "About Us" block on home page', 'asana' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => 'uni_home_about_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_about_more_link_url',
        'label'       => __( 'URL for a "view more" link for "About Us" block on home page', 'asana' ),
        'desc'        => __( 'Add custom URI', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_about_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_about_more_link_text',
        'label'       => __( 'Custom text for a "view more" link for "About Us" block on home page', 'asana' ),
        'desc'        => __( 'Add custom text. Default is: "view more"', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_about_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_enable',
        'label'       => __( 'Show/hide the grid with custom content on home page', 'asana' ),
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_promo_custom_textblock',
        'label'       => __( '6 promo items with a custom content in unique grid on home page', 'asana' ),
        'desc'        => __( 'Below you can see options to add 6 promo items with custom content in each. You are able to add custom title, text and image for every these items. Important: please keep in mind that you have to fill options for the first item or for all six items, otherwise this grid won\'t look nice. And it is required to add an URI for the item that you want to be displayed! So, to disable specific item - delete URL option for it.', 'asana' ),
        'std'         => '',
        'type'        => 'textblock',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_title_one',
        'label'       => __( 'Title for the first item in grid', 'asana' ),
        'desc'        => __( 'Add custom title for the first item in grid', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_text_one',
        'label'       => __( 'Custom text for the first item in grid', 'asana' ),
        'desc'        => __( 'Add custom text for the first item in grid', 'asana' ),
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'home',
        'rows'        => '5',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_image_one',
        'label'       => __( 'Image for the first item in grid', 'asana' ),
        'desc'        => __( 'Upload an image for the first item in grid. Thumbnail 684x684 will be shown here.', 'asana' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_uri_one',
        'label'       => __( 'URI for the first item in grid', 'asana' ),
        'desc'        => __( 'Add custom URI for the first item in grid', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_title_two',
        'label'       => __( 'Title for the second item in grid', 'asana' ),
        'desc'        => __( 'Add custom title for the second item in grid', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_text_two',
        'label'       => __( 'Custom text for the second item in grid', 'asana' ),
        'desc'        => __( 'Add custom text for the second item in grid', 'asana' ),
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'home',
        'rows'        => '5',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_image_two',
        'label'       => __( 'Image for the second item in grid', 'asana' ),
        'desc'        => __( 'Upload an image for the second item in grid. Thumbnail 342x342 will be shown here.', 'asana' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_uri_two',
        'label'       => __( 'URI for the second item in grid', 'asana' ),
        'desc'        => __( 'Add custom URI for the second item in grid', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_title_three',
        'label'       => __( 'Title for the third item in grid', 'asana' ),
        'desc'        => __( 'Add custom title for the third item in grid', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_text_three',
        'label'       => __( 'Custom text for the third item in grid', 'asana' ),
        'desc'        => __( 'Add custom text for the third item in grid', 'asana' ),
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'home',
        'rows'        => '5',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_image_three',
        'label'       => __( 'Image for the third item in grid', 'asana' ),
        'desc'        => __( 'Upload an image for the third item in grid. Thumbnail 342x342 will be shown here.', 'asana' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_uri_three',
        'label'       => __( 'URI for the third item in grid', 'asana' ),
        'desc'        => __( 'Add custom URI for the third item in grid', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_title_four',
        'label'       => __( 'Title for the fourth item in grid', 'asana' ),
        'desc'        => __( 'Add custom title for the fourth item in grid', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_text_four',
        'label'       => __( 'Custom text for the fourth item in grid', 'asana' ),
        'desc'        => __( 'Add custom text for the fourth item in grid', 'asana' ),
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'home',
        'rows'        => '5',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_image_four',
        'label'       => __( 'Image for the fourth item in grid', 'asana' ),
        'desc'        => __( 'Upload an image for the fourth item in grid. Thumbnail 342x342 will be shown here.', 'asana' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_uri_four',
        'label'       => __( 'URI for the fourth item in grid', 'asana' ),
        'desc'        => __( 'Add custom URI for the fourth item in grid', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_title_five',
        'label'       => __( 'Title for the fifth item in grid', 'asana' ),
        'desc'        => __( 'Add custom title for the fifth item in grid', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_text_five',
        'label'       => __( 'Custom text for the fifth item in grid', 'asana' ),
        'desc'        => __( 'Add custom text for the fifth item in grid', 'asana' ),
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'home',
        'rows'        => '5',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_image_five',
        'label'       => __( 'Image for the fifth item in grid', 'asana' ),
        'desc'        => __( 'Upload an image for the fifth item in grid. Thumbnail 342x342 will be shown here.', 'asana' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_uri_five',
        'label'       => __( 'URI for the fifth item in grid', 'asana' ),
        'desc'        => __( 'Add custom URI for the fifth item in grid', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_title_six',
        'label'       => __( 'Title for the sixth item in grid', 'asana' ),
        'desc'        => __( 'Add custom title for the sixth item in grid', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_text_six',
        'label'       => __( 'Custom text for the sixth item in grid', 'asana' ),
        'desc'        => __( 'Add custom text for the sixth item in grid', 'asana' ),
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'home',
        'rows'        => '5',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_image_six',
        'label'       => __( 'Image for the sixth item in grid', 'asana' ),
        'desc'        => __( 'Upload an image for the sixth item in grid. Thumbnail 684x684 will be shown here.', 'asana' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_custom_uri_six',
        'label'       => __( 'URI for the sixth item in grid', 'asana' ),
        'desc'        => __( 'Add custom URI for the sixth item in grid', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_custom_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_grid_enable',
        'label'       => __( 'Show/hide the grid with posts on home page', 'asana' ),
        'desc'        => '',
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_promo_posts_textblock',
        'label'       => __( '6 promo posts for unique grid on home page', 'asana' ),
        'desc'        => __( 'Below you can see 6 dropdowns. Please, select 6 posts here, these posts will be shown on home page in unique grid below the slider. Otherwise, 6 recent posts will be shown. Attention: if you don\'t have at least 6 published posts, this section doesn\'t appear at all! But first of all you can decide whether display or not this grid at all.', 'asana' ),
        'std'         => '',
        'type'        => 'textblock',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_posts_1',
        'label'       => __( 'Post #1', 'asana' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'custom-post-type-select',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => 'post',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_posts_2',
        'label'       => __( 'Post #2', 'asana' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'custom-post-type-select',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => 'post',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_posts_3',
        'label'       => __( 'Post #3', 'asana' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'custom-post-type-select',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => 'post',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_posts_4',
        'label'       => __( 'Post #4', 'asana' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'custom-post-type-select',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => 'post',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_posts_5',
        'label'       => __( 'Post #5', 'asana' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'custom-post-type-select',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => 'post',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_posts_6',
        'label'       => __( 'Post #6', 'asana' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'custom-post-type-select',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => 'post',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_grid_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_membership_cards_enable',
        'label'       => __( 'Show/hide membership cards section on home page', 'asana' ),
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_membership_cards_title',
        'label'       => __( 'Title for membership cards section on home page', 'asana' ),
        'desc'        => __( 'Add title for membership cards section on home page', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_membership_cards_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_shop_enable',
        'label'       => __( 'Show/hide the shop section on home page', 'asana' ),
        'desc'        => '',
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_products_type',
        'label'       => __( 'Select what products to display on home page', 'asana' ),
        'desc'        => __( 'Select an option that fits your needs. You can choose to display random products or bestsellers.', 'asana' ),
        'std'         => 'random',
        'type'        => 'select',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_shop_enable:is(on)',
        'operator'    => 'and',
        'choices'     => array(
          array(
            'value'       => '',
            'label'       => __( '-- Choose One --', 'asana' ),
            'src'         => ''
          ),
          array(
            'value'       => 'random',
            'label'       => __( 'Random', 'asana' ),
            'src'         => ''
          ),
          array(
            'value'       => 'bestsellers',
            'label'       => __( 'Bestsellers', 'asana' ),
            'src'         => ''
          )
        )
      ),
      array(
        'id'          => 'uni_home_blog_enable',
        'label'       => __( 'Show/hide a blog section on home page', 'asana' ),
        'desc'        => '',
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_textblock',
        'label'       => __( 'Classes Textblock', 'asana' ),
        'desc'        => __( 'Below are some settings for Classes block on the homepage.', 'asana' ),
        'std'         => '',
        'type'        => 'textblock',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_classes_enable',
        'label'       => __( 'Show/hide Classes block on home page?', 'asana' ),
        'desc'        => '',
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_classes_bg',
        'label'       => __( 'Image for Classes block on home page', 'asana' ),
        'desc'        => __( 'Upload an image for Classes block on home page', 'asana' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => 'uni_home_classes_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_classes_small_title',
        'label'       => __( 'Small title for Classes block on home page', 'asana' ),
        'desc'        => __( 'Add small title for Classes block on home page. Default text is "classes".', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_classes_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_classes_title',
        'label'       => __( 'Title for Classes block on home page', 'asana' ),
        'desc'        => __( 'Add title for Classes block on home page', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_classes_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_classes_button_uri',
        'label'       => __( 'URI for button for Classes block on home page', 'asana' ),
        'desc'        => __( 'Add URI for a button for Classes block on home page. Leave blank to hide this button.', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_classes_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_home_classes_button_title',
        'label'       => __( 'Title for button for Classes block on home page', 'asana' ),
        'desc'        => __( 'Add title for a button for Classes block on home page. Default text is "view classes".', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'home',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'uni_home_classes_enable:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_coordinates',
        'label'       => __( 'Google map coordinates', 'asana' ),
        'desc'        => __( 'For example: "41.404182,2.199451"', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'contact',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_zoom',
        'label'       => __( 'Google map zoom', 'asana' ),
        'desc'        => '',
        'std'         => '14',
        'type'        => 'select',
        'section'     => 'contact',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and',
        'choices'     => array(
          array(
            'value'       => '6',
            'label'       => '6',
            'src'         => ''
          ),
          array(
            'value'       => '7',
            'label'       => '7',
            'src'         => ''
          ),
          array(
            'value'       => '8',
            'label'       => '8',
            'src'         => ''
          ),
          array(
            'value'       => '9',
            'label'       => '9',
            'src'         => ''
          ),
          array(
            'value'       => '10',
            'label'       => '10',
            'src'         => ''
          ),
          array(
            'value'       => '11',
            'label'       => '11',
            'src'         => ''
          ),
          array(
            'value'       => '12',
            'label'       => '12',
            'src'         => ''
          ),
          array(
            'value'       => '13',
            'label'       => '13',
            'src'         => ''
          ),
          array(
            'value'       => '14',
            'label'       => '14',
            'src'         => ''
          ),
          array(
            'value'       => '15',
            'label'       => '15',
            'src'         => ''
          ),
          array(
            'value'       => '16',
            'label'       => '16',
            'src'         => ''
          ),
          array(
            'value'       => '17',
            'label'       => '17',
            'src'         => ''
          ),
        )
      ),
      array(
        'id'          => 'uni_address',
        'label'       => __( 'Address to be displayed on the "Contact Us" page', 'asana' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'contact',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_phone',
        'label'       => __( 'Phone number to be displayed on the "Contact Us" page', 'asana' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'contact',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_email',
        'label'       => __( 'Email to be displayed on the "Contact Us" page', 'asana' ),
        'desc'        => __( 'Also an information submitted via contact form will be sent to this email address', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'contact',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_contact_form_seven_id',
        'label'       => __( 'OR you can utilise Contact Form 7 form...', 'asana' ),
        'desc'        => __( '... Just activate your Contact Form 7 plugin and define here the ID of the form', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'contact',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_mailchimp_footer_enable',
        'label'       => __( 'Show/hide Mailchimp subscription form in the footer (affects all pages)?', 'asana' ),
        'desc'        => '',
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'mailchimp',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_mailchimp_events_enable',
        'label'       => __( 'Show/hide block with Mailchimp subscription form on "Events" page?', 'asana' ),
        'desc'        => '',
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'mailchimp',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_subscribe_header_bg',
        'label'       => __( 'Image in the background of "Subscribe" block', 'asana' ),
        'desc'        => __( 'Image in the background of block with Mailchimp subscription form on "Events" page', 'asana' ),
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'mailchimp',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => 'ot-upload-attachment-id',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_subscribe_header_title',
        'label'       => __( 'Title in "Subscribe" block', 'asana' ),
        'desc'        => __( 'Title in block with Mailchimp subscription form on "Events" page', 'asana' ),
        'std'         => 'subscribe to our newsletter',
        'type'        => 'text',
        'section'     => 'mailchimp',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_subscribe_header_subtitle',
        'label'       => __( 'Subtitle in "Subscribe" block', 'asana' ),
        'desc'        => __( 'Subtitle in block with Mailchimp subscription form on "Events" page', 'asana' ),
        'std'         => 'Subscribe and take all information about our latest events',
        'type'        => 'text',
        'section'     => 'mailchimp',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_mailchimp_api_key',
        'label'       => __( 'MailChimp API Key', 'asana' ),
        'desc'        => __( 'Add your MailChimp API Key', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'mailchimp',
        'rows'        => '5',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_mailchimp_list_id',
        'label'       => __( 'MailChimp List ID', 'asana' ),
        'desc'        => __( 'Add your MailChimp List ID', 'asana' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'mailchimp',
        'rows'        => '5',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_socials_textblock',
        'label'       => __( 'Socials Textblock', 'asana' ),
        'desc'        => __( 'Below you can add links to your social profiles. The icon of certain social media will appear only if an uri added and saved to this field.', 'asana' ),
        'std'         => '',
        'type'        => 'textblock',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_email_link',
        'label'       => __( 'Add an Email link', 'asana' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_fb_link',
        'label'       => __( 'Add a link to Facebook profile', 'asana' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_tw_link',
        'label'       => __( 'Add a link to Twitter account', 'asana' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_gp_link',
        'label'       => __( 'Add a link to Google Plus profile', 'asana' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_in_link',
        'label'       => __( 'Add a link to Instagram profile', 'asana' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_li_link',
        'label'       => __( 'Add a link to LinkedIn profile', 'asana' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_pi_link',
        'label'       => __( 'Add a link to Pinterest profile', 'asana' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_bl_link',
        'label'       => __( 'Add a link to Bloglovin account', 'asana' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_fs_link',
        'label'       => __( 'Add a link to Foursquare profile', 'asana' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_fl_link',
        'label'       => __( 'Add a link to Flickr profile', 'asana' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_dr_link',
        'label'       => __( 'Add a link to Dribble profile', 'asana' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_be_link',
        'label'       => __( 'Add a link to Behance profile', 'asana' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'uni_vk_link',
        'label'       => __( 'Add a link to Vkontakte profile', 'asana' ),
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
    )
  );

  /* settings are not the same update the DB */
  if ( $saved_settings !== $custom_settings ) {
    update_option( 'option_tree_settings', $custom_settings );
  }

}
?>